### PR TITLE
Announce Rails 3.2.14 and about the sunset of 3.2.x family to bug fixes

### PR DESCRIPTION
**Pull request by rafaelfranca**
I talked with @pixeltrix and we think is better to give people the chance to get their bug fixed in a next 3.2.x release.

@carlosantoniodasilva @fxn @jemery please review this one.

### CODE REVIEW

**Comment by steveklabnik** [comment]
I think I'm :+1: on this, as the maintenance policy should be a guarantee, not a strict set of rules. If we add another release, seems good.

That said, I think we should pick a date that 3.2.15 will be released, and announce it then, rather than leave it open-ended. Even if it's just "in 3 months, we'll evaluate if it's time to release" should put some :fire: under some people's asses.

**Comment by rafaelfranca** [comment]
Agree

**Comment by fxn** [comment]
Looking good to me.

**Comment by carlosantoniodasilva** [comment]
:shipit:

**Pull request merged**
