### PR TITLE
Import This Week in rails 2017-04-15

### PR DESCRIPTION
**Pull request by andyatkinson**

### CODE REVIEW

**Comment by andyatkinson** [comment]
@chancancode This would be out of order chronologically now, since newer posts have been written (e.g. the release of Rails 5.1). However sending it over gets more recognition for the contributors that are featured. What are your thoughts?

**Comment by andyatkinson** [comment]
Actually, I forgot how blogs work 😄 , and if this was merged/imported, it should be presented in the right spot chronologically. I did a quick render of the markdown file locally, is there a better way to make sure things look ok?

**Comment by chancancode** [comment]
I think you can just do `jekyll serve` (https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/)

but it looks good to me!

**Comment by chancancode** [comment]
http://weblog.rubyonrails.org/2017/4/15/this-week-in-rails-hooks-fixtures-fetch_values-database-connections-and-more/

**Pull request merged**
