### PR TITLE
Test how Rails Weekly looks.

### PR DESCRIPTION
**Pull request by kaspth**
Let's test how Rails weekly looks in the comfy couch of the Rails weblog :grin:

I copied the generated HTML from our latest issue straight over. It would be nice if that was all we had to do to make it look okay. We'll see :smile:

If it all checks out we could try automating the HTML extraction and Pull Request generation with a script that we add to this repo. How does that sound?

cc @dhh @chancancode

### CODE REVIEW

**Comment by claudiob** [comment]
I'm simply attaching a screenshot of applying a34a045 to make the discussion easier.

screen shot 2015-01-06 at 2 32 22 pm

**Comment by dhh** [comment]
That looks pretty broken :)

**Comment by gregmolnar** [comment]
I would remove the header image as it is too wide anyway.

**Comment by gregmolnar** [comment]
I think we should also remove all the images to make these post more inline with the current style of the post.

**Comment by chancancode** [comment]
@kaspth have you tried the HTML export for goodbits? Was it any better?

cc @pcreux @kalv

**Comment by chancancode** [comment]
If our jekyll template don't already support it, we probably need to make a "Read More" thing work, otherwise it'll take up a lot of space on the main blog page. Ideally, we would insert a "Read More" marker after the "Featured" section and people can click on it to go into the post.

**Comment by kaspth** [comment]
Okay, I've updated using the exported HTML now.

The text is still being clipped, but all the images (except logo) line up now. We also get this at the bottom of the post: 
screenshot

**Comment by kaspth** [comment]
Ugh. We already got comment spam too:
screenshot 2015-01-07 kl 16 14 52

:trollface:
A real panhandler it seems.

**Comment by pcreux** [comment]
I put together a script to export This Week in Rails to a markdown blogpost. See #23.

**Comment by kaspth** [comment]
Alright given we just had our first cross post to the blog, I think we've tested this thoroughly.

**Pull request closed without merging**
