### PR TITLE
GSoC 2014 announcement post

### PR DESCRIPTION
**Pull request by chancancode**

### CODE REVIEW

**Comment by chancancode** [comment]
cc @rafaelfranca @zzak

**Comment by chancancode** [comment]
@guilleiguaran & @febuiles as well

**Comment by febuiles** [comment]
Nice job! Three small suggestions:
- "list of projects that are accepted" => "list of projects that were accepted"
- "This is going to help both project" =>  "This is going to help both projects"
- "will be joining force on to help Robin with his project." => "will be joining forces to help Robin with his project."

**Comment by chancancode** [comment]
Thank you!! Should be all fixed now!

**Pull request merged**
